export const CoursesCardAPI = [
  // {
  //   id: 'complete-web-development-hinglish',
  //   imageUrl: 'https://www.cdmi.in/courses@2x/web-developments.webp', 
  //   title: 'Master web development (Hinglish)',
  //   description: 'Become industry level expert with this one course and build your agency or get hired or know more than your interviewer.',
  //   instructor: 'Multiple Professionals',
  //   rating: 0,
  //   reviewsCount: 0,
  //   duration: 0,
  //   lectureCount: 0,
  //   level: 'All Levels',
  //   price: 0,
  //   originalPrice: 0,
  //   isBestseller: false,
  // },
  // {
  //   id: 'master-react-js',
  //   imageUrl: 'https://www.cdmi.in/courses@2x/web-developments.webp',
  //   title: 'Master ReactJS (Hinglish)',
  //   description: 'Become industry level expert in ReactJS and know more than your interviewer.',
  //   instructor: 'Multiple professionals',
  //   rating: 0,
  //   reviewsCount: 0,
  //   duration: 0,
  //   lectureCount: 0,
  //   level: 'All Levels',
  //   price: 0,
  //   originalPrice: 0,
  //   isBestseller: false, 
  // },
  // {
  //   id: 'master-frontend-system-design',
  //   imageUrl: 'https://www.cdmi.in/courses@2x/web-developments.webp',
  //   title: 'Master Frontend System Design (Hinglish)',
  //   description: 'Become industry level expert in frontend system design and know more than your interviewer.',
  //   instructor: 'Multiple professionals',
  //   rating: 0,
  //   reviewsCount: 0,
  //   duration: 0,
  //   lectureCount: 0,
  //   level: 'All Levels',
  //   price: 0,
  //   originalPrice: 0,
  //   isBestseller: true, 
  // },
  {
    id: 'master-java',
    imageUrl: 'https://www.cdmi.in/courses@2x/web-developments.webp',
    title: 'Master Java',
    description: 'Learn Java from scratch. Level up smooth. Code with confidence.',
    instructor: 'Multiple professionals',
    rating: 0,
    reviewsCount: 0,
    duration: 0,
    lectureCount: 0,
    level: 'All Levels',
    price: 0,
    originalPrice: 0,
    isBestseller: true, 
  },
];